# -*- coding: utf-8 -*-
"""Copy of Untitled45.r

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGmdOVCOcquIsVE-0iSS4TFkz8RtQu2X
"""

import statistics as st
member_names=["santhu","shiv","Ram","krishna","keshav"]
age=[22,25,24,23,26]
workout_hrs=[2,1.5,2.5,1,3]
calories_burned=[500,350,600,300,7500]
visit_week=[6,2,3,7,5]
for i in range(len(member_names)):
    print(member_names[i],age[i],workout_hrs[i],calories_burned[i])
#average orkout
avg_workout=sum(workout_hrs)/len(workout_hrs)
print("Average orkout hours:",avg_workout)
#average calories
avg_calories=sum(calories_burned)/len(calories_burned)
print("Average Calories Burned:",avg_calories)

min_cal=min(calories_burned)
print("Minimum Calories Burned:",min_cal)
max_cal=max(calories_burned)
print("Maximum Calories Burned:",max_cal)

median_cal=st.median(calories_burned)
print("Median Calories Burned:",median_cal)

std_dev=st.stdev(calories_burned)
print("Standard Deviation of Calories Burned:",std_dev)

std_workouthrrs=round(st.stdev(workout_hrs),2)
print("Standard Deviation of Workout Hours:",std_workouthrrs)

index=calories_burned.index(max_cal)
print("Member with Maximum Calories Burned:",member_names[index])

max_visit=max(visit_week)
print("Maximum number of visits in a week:",max_visit)
index=visit_week.index(max_visit)
print("Member with Maximum number of visits in a week(Active Member):",member_names[index])

import matplotlib.pyplot as plt
plt.bar(x=member_names,height=calories_burned)
plt.xlabel("Member Names")
plt.ylabel("Calories Burned")
plt.title("Calories Burned by Members")
plt.show()

plt.bar(x=member_names,height=visit_week)
plt.xlabel("Member Names")
plt.ylabel("visit per week")
plt.title("Active Person")
plt.show()

plt.boxplot(calories_burned)
plt.ylabel("Calories Burned")
plt.title("Box Plot of Calories Burned")
plt.show()

mean_visit=st.mean(visit_week)
print("Mean number of visits in a week:",mean_visit)
median_visit=st.median(visit_week)
print("Median number of visits in a week:",median_visit)

