# -*- coding: utf-8 -*-
"""diagno ANA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBxRyU0X_DfHh4ksQCWEXCumx1XKK2QG
"""

import pandas as pd
data={"cust_name":["Ram","shiv","keshav","krishna","sathosh","ashok","Ram","shiv","ashok"],
      "cust_id":[1,2,3,4,5,6,1,2,6],
      "product":["watch","shoes","watch","shirt","chappals","pants","perfume","aaa","watch"],
      "price":[1000,999,1000,500,490,600,200,100,1000],
      "region":["east","west","south","north","north","north","east","west","north"],
      "sales":[10000,999,1000,500,1000,2000,200,300,1500],
      "Delay":[1,5,2,1,1,1,0,4,1],
      "marketing":[1000,600,100,50,1500,2000,1500,2000,1000]
      }

df=pd.DataFrame(data)
df

data_grp=df.groupby("cust_name")["sales"].sum()
data_grp
plt.pie(data_grp.values,labels=data_grp.index,autopct="%.2f%%")
plt.show()



data_grp = df.groupby("cust_name")["region"].agg(lambda x: x.mode()[0])
data_grp

data_re=df.groupby("region")["sales"].sum()
data_re

import matplotlib.pyplot as plt
plt.bar(data_re.index,data_re.values)
plt.title("Sales in each region")
plt.show()

data_gd=df.groupby("region")["Delay"].mean()
plt.bar(data_gd.index,data_gd.values)
plt.title("Delay in each region")
plt.xlabel("Region")
plt.ylabel("Delay")
plt.show()

data_mar=df.groupby("region")["marketing"].sum()
data_mar

plt.bar(data_mar.index,data_mar.values)
plt.title("Marketing in each region")
plt.xlabel("Region")
plt.ylabel("Marketing")
plt.show()

#profit
sale=df["sales"].sum()
cost=df["marketing"].sum()
profit=((sale-cost)/cost)*100
print(sale)
print(cost)
print(profit)

data_rgrp=df.groupby("region")[["sales","marketing"]].sum()
data_rgrp

data_rgrp=data_rgrp.drop("profit%",axis=1)
data_rgrp

#customer retention
retention=(3/6)*100
print(retention)















#Diagnosc Analysis

customer_names=["A","B","C","D","E"]
internet_speed=[2,10,1,15,50]
pay_fail=[3,0,4,0,2]
del_char=[200,50,250,40,60]
pur_com=[False,True,False,True,False]

for i in range(len(customer_names)):
    print(customer_names[i],internet_speed[i],pay_fail[i],del_char[i],pur_com[i])

import pandas as pd
data=pd.read_csv("/content/Amazon Sale Report.csv")
df=pd.DataFrame(data)
df

df=df.drop(["index","Style","SKU","ship-postal-code","ship-country","promotion-ids","Unnamed: 22","ASIN","currency"],axis=1)
df

df.isnull().sum()

df.dropna(inplace=True)

df.isnull().sum()

df_st=df.groupby("Status")["Amount"].sum().reset_index()
df_st

plt.bar(df_st.index,df_st.values)
plt.title("Sales in each Status")
plt.xlabel("Status")
plt.ylabel("Sales")
plt.xticks(rotation=90)
plt.show()

df_ft=df.groupby("Fulfilment")["Amount"].sum()
df_ft

df_sst=df.groupby("ship-state")["Amount"].sum().reset_index()

df_sst[["ship-state","Amount"]].min()

df_ca=df.groupby("Category")["Amount"].sum().reset_index()
df_ca

df_ca['Amount'].min()

plt.bar(df_ca["Category"],df_ca["Amount"])
plt.title("Sales in each Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.xticks(rotation=90)
plt.show()



