# -*- coding: utf-8 -*-
"""Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWWs9YMb9G2Ad3kwPkcUWwDIoBfTXUpF
"""

#1.swiggy/Zomoto Analysis

#tasks
# 1.Analyze delivary data
#   oreder time
#   delivary time
#   delivary partener
#   customer rating
# 2.Identify
#   avg delivary time
# 3.create charts,performnce reports

import pandas as pd
import matplotlib.pyplot as plt
ordertime=[2,3,7,9,5] #intime hours
delivarytime=[3,3,9,11,5] #intime hours
delivarypartner=["S","S","Z","S","Z"]
areas=["E","W","N","E","E"]
ordhrs=["8-10 AM","1-3 PM","5-7 PM","9-10 PM","12-2 AM"]
orders=[80,40,90,120,100]
customerrating=[4,4.9,3.1,2.5,5]

for i in range(len(ordertime)):
  print(ordertime[i],delivarytime[i],delivarypartner[i],customerrating[i])

delay=[]
for i in range(len(ordertime)):
  delay.append(delivarytime[i]-ordertime[i])
print(delay)

#Avg Delivary Time
avg_delivary_time=sum(delivarytime)/len(delivarytime)
print(avg_delivary_time)

avg_order_time=sum(ordertime)/len(ordertime)
delivary_time=avg_order_time-avg_delivary_time
print(delivary_time)



#Interpretation / Report
# average delivary time is 6.0 so,
# but delivary time is -1
# so Every item is delivered 1 hour late





plt.bar(x=delivarypartner,height=delivarytime)
plt.title("Delivary Time")
plt.show()

#interpretation
# delay time is more when delivary partener is "S"
# So Focus more on "S improve the delivary time make customer satisfyyy





#avg rating
avg_rate=sum(customerrating)/len(customerrating)
print(avg_rate)

#interpretation
# typical customer rating is good





df=pd.DataFrame({"ordertime":ordertime,"delivarytime":delivarytime,"delivarypartner":delivarypartner,"delay":delay,"ordhrs":ordhrs,"ordrs":orders,"customerrating":customerrating,"areas":areas})
 df_grp=df.groupby("delivarypartner")["customerrating"].mean()
 df_grp

plt.bar(x=df_grp.index,height=df_grp)
plt.title("Average Rating")
plt.show()
# "Z" partener has High rating he id doing great compared to S
#Replace or Improve that S partner

cust_leave=0
for i in range(len(ordertime)):
  if(delay[i]>=2 and customerrating[i]<=3.5):
    cust_leave=cust_leave+1
print(cust_leave)

churnrate=(cust_leave/len(ordertime))*100
print(churnrate,"%")

#customer churn rate is 40% so focus on custome aquation
# due to delay there are ready to leave so focus on fast delivary with quality.





df_ar=df.groupby("areas")["delay"].mean()
df_ar

plt.bar(x=df_ar.index,height=df_ar)
plt.title("Delay")
plt.show()

#in "N" region delays are high so focus on that region and also focus on Region "E"



#peak order hours
plt.pie(x=orders,labels=ordhrs,autopct="%.2f%%")
plt.title("Peak Order Hours")
plt.show()







2.most sold productpurchase
high revenue
customerratingmost used payments
producst with poor ratein

productname=["shoes","watch","shirt","pant","watch","shoes"]
cartabondent=[1,1,0,1,1,1]
customerratings=[3.0,4.2,2.1,4,3.5,4.0]
paymentmethod=["O","C","O","O","C","O"]
productbuied=[1,1,1,0,0,1]
custmers=["A","B","A","B","C","A"]
sales=[400,200,500,600,200,400]
for i in range(len(productname)):
  print(productname[i],cartabondent[i],customerratings[i],paymentmethod[i],productbuied[i],sales[i])

df=pd.DataFrame({"productname":productname,"customers":custmers,"cartabondent":cartabondent,"customerratings":customerratings,"paymentmethod":paymentmethod,"productbuied":productbuied,"sales":sales})
df









most_sold_product=df.groupby("productname")["productbuied"].sum()
plt.bar(x=most_sold_product.index,height=most_sold_product)
plt.title("Most Sold Product")
plt.show()

#shoes are buied more / purchased more.

high_revenue_customers=df.groupby("customers")["sales"].sum()
high_revenue_customers

#high revenue customers
high_revenue_customers=df.groupby("customers")["sales"].sum()
plt.pie(x=high_revenue_customers,labels=high_revenue_customers.index,autopct="%.2f%%")
plt.title("High Revenue Customers")
plt.show()

# A customer Buied more he generated hign revenue and B also good



most_used_payment=df['paymentmethod'].mode()
most_used_payment

#Through ONLINE most people done payment





df_ppr=df.groupby("productname")["customerratings"].mean().reset_index()
df_ppr

#customers with poor ratings
cpr=df[df['customerratings']<3.5]
cpr



cartabond=((sum(cartabondent)-sum(productbuied))/sum(cartabondent))*100
print(cartabond,"%")

#20% people just add to cart they didn't buied the products
#due to:
  1.High traffic
  2.outof stock etc.







val=[sum(cartabondent),sum(productbuied)]
val.sort()
des=["Buied Product","added to carta"]
data=pd.DataFrame({"val":val,"des":des})
data

plt.barh(y=data["des"], width=data["val"])
plt.title("Funnel Analysisss")
plt.show()







#3.Fraud Tranctions Detect

trans=[1000000,500,2000,8900000,10000,20000]
loc=["IN","IN","IN","US","IN","IN"]
banktype=["S","S","C","S","C","S"]
time=["MidNight","Evening","Morning","MidNight","Afternonn","Morning"]
for i in range(len(trans)):
  print(trans[i],loc[i],banktype[i],time[i])

df=pd.DataFrame({"trans":trans,"loc":loc,"banktype":banktype,"time":time,"fraudtrans":fraudtrans})
df

#Fraud Tractions
fd=df[(df["trans"]>=100000) | (df['loc'] != "IN")]
fd





#account and time wise fraud
facc=df[(df["trans"]>=100000) | (df['loc'] != "IN")]["time"].groupby(df["banktype"]).value_counts()
facc





fraudtrans=[]
for i in range(len(trans)):
  if trans[i]>=100000 or loc[i]!="IN":
    fraudtrans.append(1)
  else:
    fraudtrans.append(0)
print(fraudtrans)





#hirisk account
hra=df.groupby("banktype")["fraudtrans"].sum()
plt.bar(x=hra.index,height=hra)
plt.title("High Risk Account")
plt.show()

hrtme=df.groupby("time")["fraudtrans"].sum()
plt.bar(x=hrtme.index,height=hrtme)
plt.title("High Risk Time")
plt.show()





"""#Pattern of Fraud Trans

*   1.Midnight nigth Transactions
*   2.High Value Transactions and out of location
*   3.savings account.
"""







# #super market analysis

# reduce product waste and improve stock management

# dalysales
# product stock
# expiry dates

task
 1.fastmoving product
 2.slow
 3.out of stock trends
 sugg
  1.

day=[1,2,3,4,5,6]
productname=["cooldrinks","dairyproducts","basicproducts","sunscreens","umbrella","sweters"]
dailysales=[5000,6000,4000,10000,8000,10000]
productstock=[100,200,500,150,100,500]
preparedate=[1,1,0,1,1,0]
expirydates=[10,5,0,12,0,0]
seasonaldemand=["summer","summer","winter","summer","Rainy","winter"]
buied=[70,150,20,150,50,100]
for i in range(len(productname)):
  print(day[i],productname[i],dailysales[i],productstock[i],preparedate[i],expirydates[i],seasonaldemand[i],buied[i])

df=pd.DataFrame({"day":day,"productname":productname,"moving":moving,"dailysales":dailysales,"productstock":productstock,"preparedate":preparedate,"expirydates":expirydates,"seasonaldemand":seasonaldemand,"buied":buied})

df

#fast moving
curr_month=2
moving=[]
for i in range(len(day)):
  moving.append(curr_month-preparedate[i])
print(moving)

df["fsmoving%"]=(df['buied']/df['productstock'])*100
df

plt.bar(x=df["productname"],height=df["fsmoving%"])
plt.title("Fast and Slow Moving Product")
plt.xticks(rotation=90)
plt.show()

for i in range(len(day)):
  if(productstock[i]<=buied[i]):
    print(productname[i]," : out of stock")



df_sea=df.groupby("seasonaldemand")["dailysales"].sum()
df_sea

plt.bar(x=df_sea.index,height=df_sea)
plt.title("Season wie Sales")
plt.show()





df

df_sum=df[(df["buied"]>50) & (df['seasonaldemand']=="summer")]
df_sum[["productname","dailysales","seasonaldemand"]]

df_sum=df[(df["buied"]>50) & (df['seasonaldemand']=="winter")]
df_sum[["productname","dailysales","seasonaldemand"]]

df_sum=df[(df["buied"]>=50) & (df['seasonaldemand']=="Rainy")]
df_sum[["productname","dailysales","seasonaldemand"]]



in_mo=10
for i in range(len(day)):
  if(in_mo-expirydates[i]<=0):
    print(productname[i],expirydates[i]," : Expired")

