# -*- coding: utf-8 -*-
"""Untitled44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/GollaSanthosh123/AI_Health_Assistant/blob/main/Untitled44.ipynb
"""

import numpy as np
import pandas as pd
data={'marks':[90,90,78,31,31],
     'st_hrs':[10,12,7,5,2]}
df=pd.DataFrame(data)

df['marks'].describe()

df['marks'].corr(df['st_hrs'])

df['marks'].var()

df['marks'].mode()

import matplotlib.pyplot as plt
import seaborn as sns
sns.barplot(x='marks',y='st_hrs',data=df)
plt.show()

