# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBxRyU0X_DfHh4ksQCWEXCumx1XKK2QG
"""

import pandas as pd
data={"cust_name":["Ram","shiv","keshav","krishna","sathosh","ashok","Ram","shiv","ashok"],
      "cust_id":[1,2,3,4,5,6,1,2,6],
      "product":["watch","shoes","watch","shirt","chappals","pants","perfume","aaa","watch"],
      "price":[1000,999,1000,500,490,600,200,100,1000],
      "region":["east","west","south","north","north","north","east","west","north"],
      "sales":[10000,999,1000,500,1000,2000,200,300,1500],
      "Delay":[1,5,2,1,1,1,0,4,1],
      "marketing":[1000,600,100,50,1500,2000,1500,2000,1000]
      }

df=pd.DataFrame(data)
df

data_grp=df.groupby("cust_name")["sales"].sum()
data_grp
plt.pie(data_grp.values,labels=data_grp.index,autopct="%.2f%%")
plt.show()



data_grp = df.groupby("cust_name")["region"].agg(lambda x: x.mode()[0])
data_grp

data_re=df.groupby("region")["sales"].sum()
data_re

import matplotlib.pyplot as plt
plt.bar(data_re.index,data_re.values)
plt.title("Sales in each region")
plt.show()

data_gd=df.groupby("region")["Delay"].mean()
plt.bar(data_gd.index,data_gd.values)
plt.title("Delay in each region")
plt.xlabel("Region")
plt.ylabel("Delay")
plt.show()

data_mar=df.groupby("region")["marketing"].sum()
data_mar

plt.bar(data_mar.index,data_mar.values)
plt.title("Marketing in each region")
plt.xlabel("Region")
plt.ylabel("Marketing")
plt.show()

#profit
sale=df["sales"].sum()
cost=df["marketing"].sum()
profit=((sale-cost)/cost)*100
print(sale)
print(cost)
print(profit)

data_rgrp=df.groupby("region")[["sales","marketing"]].sum()
data_rgrp

data_rgrp=data_rgrp.drop("profit%",axis=1)
data_rgrp

#customer retention
retention=(3/6)*100
print(retention)

(3/9)*100

